### ISSUE TITLE
Why is this action using the CLI instead of using `caprover/deploy-from-github` to deploy?

### ISSUE THREAD

**Issue by Boscop** [adamghill/build-docker-and-deploy-to-caprover#12]
I'm curious why this action is deploying via the caprover CLI
https://github.com/adamghill/build-docker-and-deploy-to-caprover/blob/4a1b7fd7ccd1ff1981632ff6ef3aea3405c3dad8/action.yml#L88
instead of doing it as recommended here:
https://caprover.com/docs/ci-cd-integration/deploy-from-github.html#create-the-github-action
```yml
    - name: Deploy Image to CapRrover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.APP_TOKEN }}"
        image: ${{ env.IMAGE_URL }}
```
by using this action: https://github.com/caprover/deploy-from-github
:)
