### ISSUE TITLE
Docker image build process cannot read env variables

### ISSUE THREAD

**Issue by Tobi-De** [adamghill/build-docker-and-deploy-to-caprover#2]
```yaml
name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  deploy-to-caprover:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: adamghill/build-docker-and-deploy-to-caprover@main
        env:
          # This is necessary for any build process in the Dockerfile that depends on the manage.py file, such as the Tailwind CSS build or the Django collectstatic command.
          DEBUG: True
          DATABASE_URL: sqlite:///db.sqlite3
          SECRET_KEY: gALEBYPx2tX8mOdZEybvZLNQ0doWsxPRN8yEBumQF+KoPiJulVi0wKof4OqXceITfge7JXkjDuzeqtm3euNitg==

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          caprover-app-name: bookworm
          caprover-server-url: ${{ secrets.CAPROVER_SERVER_URL }}
          caprover-app-token: ${{ secrets.CAPROVER_APP_TOKEN }}
          docker-file-name: deploy/Dockerfile

```
Hi @adamghill,

I hope you're doing well! I'm currently running the workflow above based on your action. While my image builds without any issues locally, it fails when running the action. It appears that some environments are missing, which makes sense since I'm running `python manage.py collectstatic` somewhere in that [image](https://github.com/Tobi-De/falco_blueprint_basic/blob/feat/improved-settings/%7B%7B%20cookiecutter.project_name%20%7D%7D/deploy/Dockerfile#L36) and it need the project to be able to run.

I've added some basic environments  as you can see in the workflow, thinking it would solve the isssue. The specific values aren't that important; it's just for the build process. However, it seems your action cannot read these environments. Any idea what I'm doing wrong?

Thanks!
