### ISSUE TITLE
custom image name

### ISSUE THREAD

**Issue by Tobi-De** [adamghill/build-docker-and-deploy-to-caprover#3]
my github username contains some upper case character and since it is part of the imageName, docker can't pull it 

```shell
------------------------- Sun Mar 10 2024 08:08:43 GMT+0000 (Coordinated Universal Time)
Build started for bookworm
An explicit image name was provided (ghcr.io/Tobi-De/bookworm-bookworm:main). Therefore, no build process is needed.
Pulling this image: ghcr.io/Tobi-De/bookworm-bookworm:main This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 400) unexpected - invalid reference format: repository name (Tobi-De/bookworm-bookworm) must be lowercase
```

I was thinking of adding a new property like this 

```yaml
inputs:
  image-name:
    description: "The name of the docker image to build"
    required: false
    default: ${{ github.repository }}-${{ inputs.caprover-app-name }}
    
- name: Deploy image to CapRover
      run: |
        docker run caprover/cli-caprover:latest caprover deploy --host ${{ inputs.caprover-server-url }} --appToken ${{ inputs.caprover-app-token }} --appName ${{ inputs.caprover-app-name }} --imageName ${{ inputs.registry }}/${{ inputs.image-name}}:${{ inputs.branch-name }}
      shell: bash
```

**Comment by adamghill** [comment]
This would work. Do you think it would be useful to by default "slugify" `github.repository`? Maybe using something like https://github.com/gacts/github-slug (first one I found while searching)?

**Comment by Tobi-De** [comment]
> This would work. Do you think it would be useful to by default "slugify" `github.repository` and `inputs.caprover-app-name`? Maybe using something like [gacts/github-slug](https://github.com/gacts/github-slug) (first one I found while searching)?

yep, I though of that too, good idea in my optinion

**Comment by Tobi-De** [comment]
I going to see how it works and see if I can add it to #4

**Comment by Tobi-De** [comment]
@adamghill what do you think of this instead ?

````
github.repository | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z
````

**Comment by adamghill** [comment]
This works for me testing on my local. Could that be added at https://github.com/adamghill/build-docker-and-deploy-to-caprover/pull/4/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R29?

**Comment by Tobi-De** [comment]
> This works for me testing on my local. Could that be added at [#4 (files)](https://github.com/adamghill/build-docker-and-deploy-to-caprover/pull/4/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R29)?

On it.
Are you able to test the github action on local ?

**Comment by adamghill** [comment]
>Are you able to test the github action on local

No, unfortunately not. I tend to merge, tag, push, release, and _then_ go to another repo, update that action to point to the new version -- it's a mess.

Maybe https://github.com/nektos/act could help? Or is there a way to write unit tests for GitHub Actions or something?

**Comment by Tobi-De** [comment]
> No, unfortunately not. I tend to merge, tag, push, release, and then go to another repo, update that action to point to the new version -- it's a mess.

That's what I thought, and that's why I'm reluctant to push something I'm not sure will work.

```yaml
inputs:
  image-name:
    description: "The name of the docker image to build"
    required: false
    default: ${{ echo github.repository | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z }}-${{ echo inputs.caprover-app-name | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z}}
```
> Maybe [nektos/act](https://github.com/nektos/act) could help? Or is there a way to write unit tests for GitHub Actions or something?

I was thinking about this, but I'm not sure it can test a custom action, afaik it's for workflows, so I'll still need to make the action available on the marketplace to test it
